export const ADD_TO_AGENDA_REQUEST = 'ADD_TO_AGENDA_REQUEST';
export const ADD_TO_AGENDA_SUCCESS = 'ADD_TO_AGENDA_SUCCESS';
export const ADD_TO_AGENDA_FAIL = 'ADD_TO_AGENDA_FAIL';

export const TEACHER_AGENDA_REQUEST = 'TEACHER_AGENDA_REQUEST';
export const TEACHER_AGENDA_SUCCESS = 'TEACHER_AGENDA_SUCCESS';
export const TEACHER_AGENDA_FAIL = 'TEACHER_AGENDA_FAIL';

// export const UPDATE_LEVEL_REQUEST = 'UPDATE_LEVEL_REQUEST';
// export const UPDATE_LEVEL_SUCCESS = 'UPDATE_LEVEL_SUCCESS';
// export const UPDATE_LEVEL_FAIL = 'UPDATE_LEVEL_FAIL';

// export const DELETE_CLASS_REQUEST = 'DELETE_CLASS_REQUEST';
// export const DELETE_CLASS_SUCCESS = 'DELETE_CLASS_SUCCESS';
// export const DELETE_CLASS_FAIL = 'DELETE_CLASS_FAIL';
