export const ADD_CLASS_REQUEST = 'ADD_CLASS_REQUEST';
export const ADD_CLASS_SUCCESS = 'ADD_CLASS_SUCCESS';
export const ADD_CLASS_FAIL = 'ADD_CLASS_FAIL';

export const LIST_CLASSES_REQUEST = 'LIST_CLASSES_REQUEST';
export const LIST_CLASSES_SUCCESS = 'LIST_CLASSES_SUCCESS';
export const LIST_CLASSES_FAIL = 'LIST_CLASSES_FAIL';

// export const UPDATE_LEVEL_REQUEST = 'UPDATE_LEVEL_REQUEST';
// export const UPDATE_LEVEL_SUCCESS = 'UPDATE_LEVEL_SUCCESS';
// export const UPDATE_LEVEL_FAIL = 'UPDATE_LEVEL_FAIL';

export const DELETE_CLASS_REQUEST = 'DELETE_CLASS_REQUEST';
export const DELETE_CLASS_SUCCESS = 'DELETE_CLASS_SUCCESS';
export const DELETE_CLASS_FAIL = 'DELETE_CLASS_FAIL';
