export const ADD_COURSE_REQUEST = 'ADD_COURSE_REQUEST';
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE_FAIL = 'ADD_COURSE_FAIL';


export const LIST_COURSES_REQUEST = 'LIST_COURSES_REQUEST';
export const LIST_COURSES_SUCCESS = 'LIST_COURSES_SUCCESS';
export const LIST_COURSES_FAIL = 'LIST_COURSES_FAIL';


// export const UPDATE_COURSE_REQUEST = 'UPDATE_COURSE_REQUEST';
// export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
// export const UPDATE_COURSE_FAIL = 'UPDATE_COURSE_FAIL';


export const DELETE_COURSE_REQUEST = 'DELETE_COURSE_REQUEST';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_FAIL = 'DELETE_COURSE_FAIL';


export const SHOW_COURSE_REQUEST = 'SHOW_COURSE_REQUEST';
export const SHOW_COURSE_SUCCESS = 'SHOW_COURSE_SUCCESS';
export const SHOW_COURSE_FAIL = 'SHOW_COURSE_FAIL';


export const LIST_COURSE_GROUPS_REQUEST = 'LIST_COURSE_GROUPS_REQUEST';
export const LIST_COURSE_GROUPS_SUCCESS = 'LIST_COURSE_GROUPS_SUCCESS';
export const LIST_COURSE_GROUPS_FAIL = 'LIST_COURSE_GROUPS_FAIL';
