
export const CREATE_ENROLMENT_REQUEST = 'CREATE_ENROLMENT_REQUEST';
export const CREATE_ENROLMENT_SUCCESS = 'CREATE_ENROLMENT_SUCCESS';
export const CREATE_ENROLMENT_FAIL = 'CREATE_ENROLMENT_FAIL';


export const SHOW_ENROLMENT_REQUEST = 'SHOW_ENROLMENT_REQUEST';
export const SHOW_ENROLMENT_SUCCESS = 'SHOW_ENROLMENT_SUCCESS';
export const SHOW_ENROLMENT_FAIL = 'SHOW_ENROLMENT_FAIL';


export const DELETE_ENROLMENT_REQUEST = 'DELETE_ENROLMENT_REQUEST';
export const DELETE_ENROLMENT_SUCCESS = 'DELETE_ENROLMENT_SUCCESS';
export const DELETE_ENROLMENT_FAIL = 'DELETE_ENROLMENT_FAIL';
