export const ADD_LEVEL_REQUEST = 'ADD_LEVEL_REQUEST';
export const ADD_LEVEL_SUCCESS = 'ADD_LEVEL_SUCCESS';
export const ADD_LEVEL_FAIL = 'ADD_LEVEL_FAIL';

export const LIST_LEVELS_REQUEST = 'LIST_LEVELS_REQUEST';
export const LIST_LEVELS_SUCCESS = 'LIST_LEVELS_SUCCESS';
export const LIST_LEVELS_FAIL = 'LIST_LEVELS_FAIL';

// export const UPDATE_LEVEL_REQUEST = 'UPDATE_LEVEL_REQUEST';
// export const UPDATE_LEVEL_SUCCESS = 'UPDATE_LEVEL_SUCCESS';
// export const UPDATE_LEVEL_FAIL = 'UPDATE_LEVEL_FAIL';

export const DELETE_LEVEL_REQUEST = 'DELETE_LEVEL_REQUEST';
export const DELETE_LEVEL_SUCCESS = 'DELETE_LEVEL_SUCCESS';
export const DELETE_LEVEL_FAIL = 'DELETE_LEVEL_FAIL';
