export const ADD_PLAN_REQUEST = 'ADD_PLAN_REQUEST';
export const ADD_PLAN_SUCCESS = 'ADD_PLAN_SUCCESS';
export const ADD_PLAN_FAIL = 'ADD_PLAN_FAIL';

export const LIST_PLANS_REQUEST = 'LIST_PLANS_REQUEST';
export const LIST_PLANS_SUCCESS = 'LIST_PLANS_SUCCESS';
export const LIST_PLANS_FAIL = 'LIST_PLANS_FAIL';

// export const UPDATE_PLAN_REQUEST = 'UPDATE_PLAN_REQUEST';
// export const UPDATE_PLAN_SUCCESS = 'UPDATE_PLAN_SUCCESS';
// export const UPDATE_PLAN_FAIL = 'UPDATE_PLAN_FAIL';

export const DELETE_PLAN_REQUEST = 'DELETE_PLAN_REQUEST';
export const DELETE_PLAN_SUCCESS = 'DELETE_PLAN_SUCCESS';
export const DELETE_PLAN_FAIL = 'DELETE_PLAN_FAIL';
