export const ADD_STUDENT_REQUEST = 'ADD_STUDENT_REQUEST';
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';
export const ADD_STUDENT_FAIL = 'ADD_STUDENT_FAIL';


export const LIST_STUDENTS_REQUEST = 'LIST_STUDENTS_REQUEST';
export const LIST_STUDENTS_SUCCESS = 'LIST_STUDENTS_SUCCESS';
export const LIST_STUDENTS_FAIL = 'LIST_STUDENTS_FAIL';

// export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST';
// export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
// export const UPDATE_STUDENT_FAIL = 'UPDATE_STUDENT_FAIL';

export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAIL = 'DELETE_STUDENT_FAIL';


export const SHOW_STUDENT_REQUEST = 'SHOW_STUDENT_REQUEST';
export const SHOW_STUDENT_SUCCESS = 'SHOW_STUDENT_SUCCESS';
export const SHOW_STUDENT_FAIL = 'SHOW_STUDENT_FAIL';
