export const TEACHERS_LIST_REQUEST = 'TEACHERS_LIST_REQUEST';
export const TEACHERS_LIST_SUCCESS = 'TEACHERS_LIST_SUCCESS';
export const TEACHERS_LIST_FAIL = 'TEACHERS_LIST_FAIL';




// CRUD
export const ADD_TEACHER_REQUEST = 'ADD_TEACHER_REQUEST';
export const ADD_TEACHER_SUCCESS = 'ADD_TEACHER_SUCCESS';
export const ADD_TEACHER_FAIL = 'ADD_TEACHER_FAIL';

export const SHOW_TEACHER_REQUEST = 'SHOW_TEACHER_REQUEST';
export const SHOW_TEACHER_SUCCESS = 'SHOW_TEACHER_SUCCESS';
export const SHOW_TEACHER_FAIL = 'SHOW_TEACHER_FAIL';

export const UPDATE_TEACHER_REQUEST = 'UPDATE_TEACHER_REQUEST';
export const UPDATE_TEACHER_SUCCESS = 'UPDATE_TEACHER_SUCCESS';
export const UPDATE_TEACHER_FAIL = 'UPDATE_TEACHER_FAIL';

export const DELETE_TEACHER_REQUEST = 'DELETE_TEACHER_REQUEST';
export const DELETE_TEACHER_SUCCESS = 'DELETE_TEACHER_SUCCESS';
export const DELETE_TEACHER_FAIL = 'DELETE_TEACHER_FAIL';
