export const products = [
    {
        _id: '0',
        name: 'Amazon Echo Dot Lorem ipsum, dolor sit amet consectetur adipisicing elit',
        image: '/assets/categories/1.png',
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perferendis neque, officiis illum nobis quisquam id saepe quis vitae maiores molestiae?',
        brand: 'Amazon',
        category: 'Electronics',
        price: 29,
        cent: 99,
        countInStock: 0,
        rating: 4,
        numReviews: 4
    },
    {
        _id: '1',
        name: 'Google Echo Dot Lorem ipsum, dolor sit amet consectetur adipisicing elit',
        image: '/assets/categories/2.png',
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perferendis neque, officiis illum nobis quisquam id saepe quis vitae maiores molestiae?',
        brand: 'Google',
        category: 'Electronics',
        price: 40,
        cent: 99,
        countInStock: 0,
        rating: 4,
        numReviews: 4
    },
    {
        _id: '2',
        name: 'HP Echo Dot Lorem ipsum, dolor sit amet consectetur adipisicing elit',
        image: '/assets/categories/3.png',
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perferendis neque, officiis illum nobis quisquam id saepe quis vitae maiores molestiae?',
        brand: 'HP',
        category: 'Electronics',
        price: 25,
        cent: 70,
        countInStock: 0,
        rating: 4,
        numReviews: 2
    },
    {
        _id: '3',
        name: 'DELL Echo Dot Lorem ipsum, dolor sit amet consectetur adipisicing elit',
        image: '/assets/categories/4.png',
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perferendis neque, officiis illum nobis quisquam id saepe quis vitae maiores molestiae?',
        brand: 'DELL',
        category: 'Electronics',
        price: 10,
        cent: 90,
        countInStock: 1,
        rating: 3,
        numReviews: 2
    },
    {
        _id: '4',
        name: 'ASUS LapTop i5 8th Lorem ipsum, dolor sit amet consectetur adipisicing elit',
        image: '/assets/categories/10.png',
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perferendis neque, officiis illum nobis quisquam id saepe quis vitae maiores molestiae?',
        brand: 'ASUS',
        category: 'Electronics',
        price: 499,
        cent: 25,
        countInStock: 2,
        rating: 4,
        numReviews: 4
    },
    {
        _id: '5',
        name: 'Lenevo ThinkPad Echo Dot Lorem ipsum, dolor sit amet consectetur adipisicing elit',
        image: '/assets/categories/11.png',
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perferendis neque, officiis illum nobis quisquam id saepe quis vitae maiores molestiae?',
        brand: 'lenovo',
        category: 'Electronics',
        price: 699,
        cent: 10,
        countInStock: 6,
        rating: 3,
        numReviews: 3
    },
    {
        _id: '6',
        name: 'Lenevo ThinkPad Echo Dot Lorem ipsum, dolor sit amet consectetur adipisicing elit',
        image: '/assets/categories/12.png',
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perferendis neque, officiis illum nobis quisquam id saepe quis vitae maiores molestiae?',
        brand: 'lenovo',
        category: 'Electronics',
        price: 699,
        cent: 99,
        countInStock: 6,
        rating: 3,
        numReviews: 3
    },
    {
        _id: '7',
        name: 'Lenevo ThinkPad Echo Dot Lorem ipsum, dolor sit amet consectetur adipisicing elit',
        image: '/assets/categories/13.png',
        description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perferendis neque, officiis illum nobis quisquam id saepe quis vitae maiores molestiae?',
        brand: 'lenovo',
        category: 'Electronics',
        price: 699,
        cent: 99,
        countInStock: 6,
        rating: 3,
        numReviews: 3
    },
]